import React, {useEffect, useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {Search, ShoppingCart, User, Heart, Star, ArrowRight, Check, X, Menu, Download, LayoutDashboard, Package, Settings, Plus, Trash2, ExternalLink, Sparkles, ShieldCheck, Code2, FileText, Presentation, MessageCircle, ChevronRight} from "lucide-react";
import "./styles.css";

const projects = [
 {id:1,title:"AI Viva Simulator",category:"AI / ML",stack:["Python","React","LLM"],price:999,rating:4.9,sales:186,featured:true,level:"Major",icon:"🤖",tag:"Trending",desc:"Upload a project report and practice an AI-powered viva with adaptive technical questions, scoring and weak-area recommendations.",features:["PDF/project context extraction","Adaptive viva questions","Answer scoring","Weak-area dashboard","Practice history"],includes:["Source code","Database schema","Report template","PPT","Setup guide","Viva question bank"],color:"lavender"},
 {id:2,title:"AI Resume & Job Matcher",category:"AI / ML",stack:["Python","NLP","Streamlit"],price:799,rating:4.8,sales:241,featured:true,level:"Major",icon:"📄",tag:"Popular",desc:"Analyze a resume, compare it with a job description, identify skill gaps and generate a practical improvement plan.",features:["Resume parsing","Job match score","Skill-gap analysis","Keyword insights","Dashboard"],includes:["Source code","Sample resumes","Report","PPT","Database","Deployment guide"],color:"blue"},
 {id:3,title:"Lost & Found AI",category:"Computer Vision",stack:["Python","OpenCV","React"],price:899,rating:4.7,sales:127,featured:true,level:"Major",icon:"🔍",tag:"New",desc:"A campus lost-and-found platform that uses image similarity and metadata to connect found items with reports.",features:["Image upload","Similarity matching","Claim workflow","Admin moderation","Search & filters"],includes:["Source code","Database","Report","PPT","Demo dataset","Setup guide"],color:"peach"},
 {id:4,title:"Smart Canteen Predictor",category:"Data Science",stack:["Python","Pandas","ML"],price:699,rating:4.8,sales:98,level:"Mini",icon:"🍱",tag:"",desc:"Predict daily food demand from historical sales to help a college canteen reduce overproduction and waste.",features:["Demand forecasting","Food-wise analytics","Waste estimate","Charts","CSV import"],includes:["Source code","Dataset","Notebook","Report","PPT","Viva questions"],color:"mint"},
 {id:5,title:"SkillSwap Campus",category:"Web Development",stack:["React","Node.js","MongoDB"],price:899,rating:4.6,sales:84,level:"Major",icon:"🤝",tag:"",desc:"A campus community where students exchange skills, discover peers and request one-to-one learning sessions.",features:["Student profiles","Skill matching","Requests","Messaging UI","Admin panel"],includes:["Source code","API docs","Database","Report","PPT","Deployment guide"],color:"rose"},
 {id:6,title:"Smart Complaint Analyzer",category:"NLP",stack:["Python","NLP","MySQL"],price:599,rating:4.7,sales:73,level:"Mini",icon:"📝",tag:"",desc:"Automatically classify, prioritize and summarize campus complaints for administrators.",features:["Complaint classification","Priority scoring","Keyword extraction","Admin dashboard","Reports"],includes:["Source code","Dataset","Database","Report","PPT","Viva questions"],color:"sky"},
 {id:7,title:"Campus Carbon Tracker",category:"Sustainability",stack:["React","Python","Charts"],price:749,rating:4.6,sales:52,level:"Major",icon:"🌱",tag:"",desc:"Track campus energy, transport and food-waste indicators and estimate a simple carbon footprint.",features:["Activity logging","Carbon estimates","Trend charts","Department comparison","Export"],includes:["Source code","Calculation model","Report","PPT","Dataset","Setup guide"],color:"mint"},
 {id:8,title:"AI Notes → Quiz Generator",category:"AI / ML",stack:["Python","React","LLM"],price:649,rating:4.9,sales:156,level:"Mini",icon:"🧠",tag:"Trending",desc:"Turn study notes into MCQs, short-answer questions and revision quizzes with difficulty controls.",features:["PDF/text input","Question generation","Difficulty levels","Quiz mode","Score history"],includes:["Source code","Sample notes","Report","PPT","Setup guide","Viva questions"],color:"lavender"},
 {id:9,title:"College Club Matchmaker",category:"Web Development",stack:["React","Node.js","MySQL"],price:599,rating:4.5,sales:44,level:"Mini",icon:"🎯",tag:"",desc:"Recommend student clubs and events based on interests, skills and activity preferences.",features:["Interest profile","Recommendations","Club pages","Event registration","Admin panel"],includes:["Source code","Database","Report","PPT","Demo data","Setup guide"],color:"blue"},
 {id:10,title:"Virtual Queue Manager",category:"Web Development",stack:["React","Node.js","MySQL"],price:549,rating:4.6,sales:67,level:"Mini",icon:"🎟️",tag:"",desc:"A digital token system for college offices, labs, libraries and canteens.",features:["Token generation","Live queue","Notifications UI","Counter dashboard","Reports"],includes:["Source code","Database","Report","PPT","API docs","Setup guide"],color:"peach"},
 {id:11,title:"Fake Internship Detector",category:"AI / ML",stack:["Python","NLP","Streamlit"],price:799,rating:4.7,sales:61,level:"Major",icon:"🛡️",tag:"New",desc:"Analyze internship listings for suspicious patterns and produce transparent risk indicators.",features:["Listing analysis","Pattern detection","Risk indicators","Evidence highlights","History"],includes:["Source code","Dataset","Notebook","Report","PPT","Viva questions"],color:"rose"},
 {id:12,title:"Project Plagiarism Analyzer",category:"Developer Tools",stack:["Python","NLP","React"],price:899,rating:4.8,sales:39,level:"Major",icon:"🧩",tag:"",desc:"Compare project descriptions, documentation and code snippets for similarity and produce an explainable report.",features:["Text similarity","Code comparison","Similarity report","History","Export"],includes:["Source code","Test data","Report","PPT","Setup guide","API docs"],color:"sky"}
];

const categories = ["All","AI / ML","Web Development","Data Science","Computer Vision","NLP","Sustainability","Developer Tools"];
const nav = [{id:"home",label:"Home"},{id:"projects",label:"Projects"},{id:"how",label:"How it works"}];

function App(){
 const [page,setPage]=useState("home"), [query,setQuery]=useState(""), [category,setCategory]=useState("All");
 const [selected,setSelected]=useState(null), [cart,setCart]=useState([]), [liked,setLiked]=useState([]), [mobile,setMobile]=useState(false);
 const [dashboard,setDashboard]=useState("purchases");
 const [toast,setToast]=useState("");
 const [adminProjects,setAdminProjects]=useState(projects);
 const [showCart,setShowCart]=useState(false);

 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2200);return()=>clearTimeout(t)}},[toast]);

 const filtered=useMemo(()=>adminProjects.filter(p=>(category==="All"||p.category===category)&&(`${p.title} ${p.category} ${p.stack.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[adminProjects,category,query]);
 const addCart=(p)=>{if(!cart.some(x=>x.id===p.id)){setCart([...cart,p]);setToast("Added to cart")}else setToast("Already in cart")};
 const removeCart=(id)=>setCart(cart.filter(x=>x.id!==id));
 const buyNow=(p)=>{addCart(p);setShowCart(true)};
 const go=(p)=>{setPage(p);setMobile(false);window.scrollTo({top:0,behavior:"smooth"})};

 return <div className="app">
  <header className="header">
   <div className="container navrow">
    <button className="brand" onClick={()=>go("home")}><span className="logo"><Sparkles size={18}/></span><span>Project<span>Hub</span></span></button>
    <nav className={mobile?"nav open":"nav"}>{nav.map(n=><button key={n.id} className={page===n.id?"active":""} onClick={()=>go(n.id)}>{n.label}</button>)}</nav>
    <div className="navactions">
      <button className="iconbtn" onClick={()=>go("dashboard")} title="Dashboard"><User size={19}/></button>
      <button className="cartbtn" onClick={()=>setShowCart(true)}><ShoppingCart size={18}/><span>Cart</span>{cart.length>0&&<b>{cart.length}</b>}</button>
      <button className="menubtn" onClick={()=>setMobile(!mobile)}><Menu/></button>
    </div>
   </div>
  </header>

  {page==="home"&&<Home go={go} projects={adminProjects} addCart={addCart} setSelected={setSelected}/>}
  {page==="projects"&&<Projects filtered={filtered} query={query} setQuery={setQuery} category={category} setCategory={setCategory} setSelected={setSelected} addCart={addCart} liked={liked} setLiked={setLiked}/>}
  {page==="how"&&<How go={go}/>}
  {page==="dashboard"&&<Dashboard tab={dashboard} setTab={setDashboard} cart={cart} removeCart={removeCart} setSelected={setSelected} adminProjects={adminProjects} setAdminProjects={setAdminProjects} setToast={setToast}/>}
  <footer><div className="container foot"><div><div className="brand footerbrand"><span className="logo"><Sparkles size={16}/></span>Project<span>Hub</span></div><p>Modern, demo-ready project kits for students.</p></div><div><strong>Explore</strong><button onClick={()=>go("projects")}>All projects</button><button onClick={()=>go("how")}>How it works</button></div><div><strong>Support</strong><button onClick={()=>setToast("Support: support@projecthub.demo")}>Contact support</button><button onClick={()=>setToast("Customization requests are available after purchase.")}>Customization</button></div></div><div className="copyright">© 2026 ProjectHub · Built for learning, demos and project practice.</div></footer>

  {selected&&<Modal p={selected} close={()=>setSelected(null)} addCart={addCart} buyNow={buyNow}/>}
  {showCart&&<Cart cart={cart} close={()=>setShowCart(false)} removeCart={removeCart} go={go}/>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Home({go,projects,addCart,setSelected}){
 return <main>
  <section className="hero"><div className="container heroGrid"><div><div className="eyebrow"><Sparkles size={14}/> Project marketplace for students</div><h1>Build something <em>worth showing.</em></h1><p className="heroText">Explore modern, customizable college projects with source code, documentation, demos and viva preparation — all in one place.</p><div className="searchbox"><Search size={19}/><input placeholder="Search AI, React, Python, data science..." onFocus={()=>go("projects")}/><button onClick={()=>go("projects")}>Explore</button></div><div className="trust"><span><Check/> Demo-ready</span><span><Check/> Documentation</span><span><Check/> Customizable</span></div></div><div className="heroCard"><div className="floatBadge">🔥 Trending this week</div><div className="mockIcon">🤖</div><h3>AI Viva Simulator</h3><p>Practice project-specific viva questions with adaptive feedback.</p><div className="mockstats"><span>⭐ 4.9</span><span>186 students</span><strong>₹999</strong></div><button className="primary full" onClick={()=>setSelected(projects[0])}>View project <ArrowRight size={16}/></button></div></div></section>

  <section className="section"><div className="container"><div className="sectionHead"><div><span className="eyebrow small">Explore</span><h2>Projects students actually want to demo</h2></div><button className="textbtn" onClick={()=>go("projects")}>View all <ArrowRight size={16}/></button></div><div className="cards">{projects.filter(p=>p.featured).slice(0,6).map(p=><ProjectCard key={p.id} p={p} setSelected={setSelected} addCart={addCart}/>)}</div></div></section>

  <section className="section categories"><div className="container"><div className="sectionHead"><div><span className="eyebrow small">Browse by stack</span><h2>Find your technology</h2></div></div><div className="catgrid">{["AI / ML","Web Development","Data Science","Computer Vision","NLP","Developer Tools"].map((c,i)=><button key={c} onClick={()=>go("projects")}><span>{["🤖","🌐","📊","👁️","💬","🧩"][i]}</span><div><strong>{c}</strong><small>{projects.filter(p=>p.category===c).length||"Many"} projects</small></div><ChevronRight size={17}/></button>)}</div></div></section>

  <section className="section howPreview"><div className="container"><div className="sectionHead center"><div><span className="eyebrow small">Simple process</span><h2>From idea to viva-ready</h2></div></div><div className="steps"><Step n="01" icon={<Search/>} title="Choose a project" text="Filter by department, stack, level and budget."/><Step n="02" icon={<Code2/>} title="Try the demo" text="Understand the features before you decide."/><Step n="03" icon={<Download/>} title="Get the kit" text="Access source code, docs, PPT and project resources."/><Step n="04" icon={<MessageCircle/>} title="Prepare your viva" text="Use the included questions and customization guide." /></div></div></section>
 </main>
}

function Step({n,icon,title,text}){return <div className="step"><span>{n}</span><div className="stepIcon">{icon}</div><h3>{title}</h3><p>{text}</p></div>}

function Projects({filtered,query,setQuery,category,setCategory,setSelected,addCart,liked,setLiked}){
 return <main className="page"><div className="container"><div className="pageIntro"><span className="eyebrow small">Project library</span><h1>Find your next project</h1><p>Modern ideas across AI, web, data, mobile and developer tools.</p></div><div className="filterbar"><div className="searchbox"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects or technologies..."/></div><div className="chips">{categories.map(c=><button className={category===c?"selected":""} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div></div><div className="resultsLine"><span>{filtered.length} projects</span><span>Source code + documentation included</span></div><div className="cards">{filtered.map(p=><ProjectCard key={p.id} p={p} setSelected={setSelected} addCart={addCart} liked={liked} setLiked={setLiked}/>)}</div>{filtered.length===0&&<div className="empty"><div>🔎</div><h3>No projects found</h3><p>Try another keyword or category.</p></div>}</div></main>
}

function ProjectCard({p,setSelected,addCart,liked=[],setLiked=()=>{}}){
 const isLiked=liked.includes(p.id);
 return <article className="card"><div className={`cardVisual ${p.color}`}><span className="projectEmoji">{p.icon}</span>{p.tag&&<span className="tag">{p.tag}</span>}<button className={isLiked?"heart liked":"heart"} onClick={()=>setLiked(isLiked?liked.filter(x=>x!==p.id):[...liked,p.id])}><Heart size={17} fill={isLiked?"currentColor":"none"}/></button></div><div className="cardBody"><div className="meta"><span>{p.category}</span><span>•</span><span>{p.level}</span></div><h3>{p.title}</h3><p>{p.desc}</p><div className="stack">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="rating"><Star size={14} fill="currentColor"/><b>{p.rating}</b><span>({p.sales})</span></div><div className="cardBottom"><strong>₹{p.price.toLocaleString("en-IN")}</strong><div><button className="outline" onClick={()=>setSelected(p)}>Details</button><button className="primary" onClick={()=>addCart(p)}>Add</button></div></div></div></article>
}

function Modal({p,close,addCart,buyNow}){
 return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="close" onClick={close}><X/></button><div className={`modalHero ${p.color}`}><span className="projectEmoji big">{p.icon}</span><div><span className="tag">{p.tag||"Project kit"}</span><h2>{p.title}</h2><p>{p.desc}</p></div></div><div className="modalGrid"><div><h4>What's included</h4><ul className="include">{p.includes.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><h4>Key features</h4><ul className="featurelist">{p.features.map(x=><li key={x}>{x}</li>)}</ul></div><aside><div className="price">₹{p.price.toLocaleString("en-IN")}</div><div className="rating"><Star size={14} fill="currentColor"/><b>{p.rating}</b><span>from {p.sales} purchases</span></div><div className="stack modalstack">{p.stack.map(s=><span key={s}>{s}</span>)}</div><button className="primary full" onClick={()=>buyNow(p)}>Buy project kit</button><button className="outline full" onClick={()=>{addCart(p);close()}}>Add to cart</button><small><ShieldCheck size={13}/> Secure checkout · Instant access after purchase</small></aside></div></div></div>
}

function Cart({cart,close,removeCart,go}){
 const total=cart.reduce((a,p)=>a+p.price,0);
 return <div className="overlay"><div className="cartPanel"><div className="panelHead"><h2>Your cart</h2><button className="close" onClick={close}><X/></button></div>{cart.length===0?<div className="empty"><div>🛒</div><h3>Your cart is empty</h3><button className="primary" onClick={()=>{close();go("projects")}}>Explore projects</button></div>:<><div className="cartItems">{cart.map(p=><div className="cartItem" key={p.id}><div className={`mini ${p.color}`}>{p.icon}</div><div><strong>{p.title}</strong><small>{p.stack.join(" · ")}</small></div><b>₹{p.price}</b><button onClick={()=>removeCart(p.id)}><Trash2 size={16}/></button></div>)}</div><div className="checkout"><span>Total</span><strong>₹{total.toLocaleString("en-IN")}</strong><button className="primary full" onClick={()=>alert("Demo checkout — connect Razorpay/Stripe here for production.")}>Proceed to checkout</button><small>Demo mode: payment gateway is not connected yet.</small></div></>}</div></div>
}

function How({go}){return <main className="page"><div className="container narrow"><div className="pageIntro center"><span className="eyebrow small">How it works</span><h1>Everything students need, in one kit.</h1><p>ProjectHub is designed around learning, customization and a clean demo experience.</p></div><div className="howCards"><div><div className="bigNum">01</div><h2>Explore</h2><p>Search by technology, category or project level. Every listing explains what the project does and what you'll receive.</p></div><div><div className="bigNum">02</div><h2>Understand</h2><p>Use the demo and feature list to choose something you can actually understand, explain and customize.</p></div><div><div className="bigNum">03</div><h2>Learn & customize</h2><p>Use the source code, documentation, sample data and setup guide as a starting point for your own implementation.</p></div></div><div className="notice"><ShieldCheck/><div><strong>Built for learning</strong><p>Students should understand and adapt their projects rather than submit someone else's work unchanged.</p></div></div><button className="primary centered" onClick={()=>go("projects")}>Explore projects <ArrowRight size={16}/></button></div></main>}

function Dashboard({tab,setTab,cart,removeCart,setSelected,adminProjects,setAdminProjects,setToast}){
 const [newTitle,setNewTitle]=useState(""); const [newPrice,setNewPrice]=useState("699");
 const [showForm,setShowForm]=useState(false);
 const purchases=cart.length?cart:adminProjects.slice(0,2);
 return <main className="page"><div className="container dash"><div className="dashTop"><div><span className="eyebrow small">Student workspace</span><h1>Dashboard</h1></div><button className="outline" onClick={()=>setToast("Account settings are demo-only in this version.")}><Settings size={16}/> Settings</button></div><div className="dashLayout"><aside className="side"><button className={tab==="purchases"?"on":""} onClick={()=>setTab("purchases")}><Package/> My projects</button><button className={tab==="favorites"?"on":""} onClick={()=>setTab("favorites")}><Heart/> Favorites</button><button className={tab==="admin"?"on":""} onClick={()=>setTab("admin")}><LayoutDashboard/> Admin catalog</button></aside><section className="dashContent">{tab==="purchases"&&<><div className="dashTitle"><div><h2>My projects</h2><p>Your project kits and quick access.</p></div><span className="pill">{cart.length} in cart</span></div><div className="purchaseGrid">{purchases.map(p=><div className="purchase" key={p.id}><div className={`mini large ${p.color}`}>{p.icon}</div><div><h3>{p.title}</h3><small>{p.category} · {p.stack.join(" · ")}</small><div className="purchaseActions"><button onClick={()=>setSelected(p)} className="outline">View</button><button onClick={()=>setToast("Demo download: connect file storage to enable downloads.")}><Download size={14}/> Download</button></div></div></div>)}</div></>}{tab==="favorites"&&<div className="empty"><div>❤️</div><h3>Your favorites live here</h3><p>Tap the heart on any project to save it.</p></div>}{tab==="admin"&&<><div className="dashTitle"><div><h2>Admin catalog</h2><p>Demo controls for managing your project listings.</p></div><button className="primary" onClick={()=>setShowForm(!showForm)}><Plus size={16}/> Add project</button></div>{showForm&&<div className="adminForm"><input placeholder="Project title" value={newTitle} onChange={e=>setNewTitle(e.target.value)}/><input placeholder="Price" value={newPrice} onChange={e=>setNewPrice(e.target.value)}/><button className="primary" onClick={()=>{if(!newTitle)return;setAdminProjects([{id:Date.now(),title:newTitle,category:"Web Development",stack:["React","Node.js"],price:Number(newPrice)||699,rating:5,sales:0,level:"Mini",icon:"✨",desc:"New custom project listing.",features:["Custom feature"],includes:["Source code","Documentation","PPT"],color:"lavender"},...adminProjects]);setNewTitle("");setShowForm(false);setToast("Project added")}}>Create</button></div>}<div className="adminTable">{adminProjects.map(p=><div key={p.id}><div className={`mini ${p.color}`}>{p.icon}</div><strong>{p.title}</strong><span>{p.category}</span><b>₹{p.price}</b><button onClick={()=>{setAdminProjects(adminProjects.filter(x=>x.id!==p.id));setToast("Project removed")}}><Trash2 size={15}/></button></div>)}</div></>}</section></div></div></main>
}

createRoot(document.getElementById("root")).render(<App/>);